"""Deterministic Week 1 triage agent and future LLM extension point."""

from __future__ import annotations

from typing import Any

from backend.models.schemas import Alert, TriageResult


class LLMNotConfiguredError(RuntimeError):
    """Raised because the provider-specific LLM adapter is not implemented yet."""


def extract_iocs(alert: Alert) -> list[str]:
    """Extract known structured values for future enrichment and correlation."""

    candidates: list[Any] = [
        alert.source_ip,
        alert.destination_ip,
        alert.host,
        alert.user,
    ]
    for key in ("hash", "file_hash", "sha256", "md5"):
        candidates.append(alert.metadata.get(key))

    iocs: list[str] = []
    for value in candidates:
        if value is None or not str(value).strip():
            continue
        normalized = str(value).strip()
        if normalized not in iocs:
            iocs.append(normalized)
    return iocs


def _search(alert: Alert, *terms: str) -> bool:
    """Return whether any term appears in the alert's searchable text."""

    searchable = f"{alert.event_type} {alert.description}".lower()
    return any(term.lower() in searchable for term in terms)


def _number(metadata: dict[str, Any], *keys: str) -> int | None:
    """Read a numeric metadata value without allowing malformed data to fail triage."""

    for key in keys:
        value = metadata.get(key)
        if isinstance(value, bool):
            continue
        if isinstance(value, (int, float)):
            return int(value)
        if isinstance(value, str) and value.isdigit():
            return int(value)
    return None


class DeterministicTriageAgent:
    """Transparent rules baseline for future agent/LLM evaluation."""

    def triage(self, alert: Alert) -> TriageResult:
        """Classify one alert using ordered, inspectable rules."""

        metadata = alert.metadata
        iocs = extract_iocs(alert)
        login_success = bool(metadata.get("login_success_after_failures"))
        approved_activity = bool(metadata.get("approved_activity"))
        ports_contacted = _number(metadata, "ports_contacted", "unique_ports")

        if approved_activity or _search(alert, "known internal vulnerability scanner", "approved admin"):
            return self._result(
                alert,
                classification="likely_false_positive",
                category="approved_activity",
                severity="low",
                confidence=0.97,
                reasoning="The alert describes activity identified as approved or generated by a known internal scanner.",
                investigations=["asset_inventory", "change_ticket"],
                next_step="Verify that the activity remains within the approved scope and close as benign if confirmed.",
                iocs=iocs,
            )

        failed_attempts = alert.failed_attempts or 0
        brute_force = (
            failed_attempts >= 5
            or _search(alert, "brute force", "repeated failed ssh", "password spray")
        )
        if brute_force:
            severity = "high" if login_success or failed_attempts >= 10 else "medium"
            confidence = 0.95 if login_success else 0.88
            return self._result(
                alert,
                classification="likely_true_positive",
                category="brute_force",
                severity=severity,
                confidence=confidence,
                reasoning=(
                    "Repeated authentication failures indicate brute-force activity; a subsequent successful "
                    "login increases the likelihood of compromise."
                    if login_success
                    else "Repeated authentication failures indicate a likely brute-force attempt."
                ),
                investigations=["authentication_logs", "source_ip_reputation", "endpoint_activity"],
                next_step="Correlate authentication and endpoint activity before any response action.",
                iocs=iocs,
            )

        if failed_attempts <= 3 and _search(alert, "mistyped password", "password typo", "user typo"):
            return self._result(
                alert,
                classification="likely_false_positive",
                category="authentication",
                severity="low",
                confidence=0.94,
                reasoning="A small number of failed logins is consistent with an ordinary user password typo.",
                investigations=["authentication_logs"],
                next_step="Confirm there is no broader failure pattern and close as benign if consistent.",
                iocs=iocs,
            )

        port_scan = (
            ports_contacted is not None and ports_contacted >= 10
        ) or _search(alert, "port scan", "many ports", "probes ports")
        if port_scan:
            severity = "high" if ports_contacted is not None and ports_contacted >= 50 else "medium"
            return self._result(
                alert,
                classification="likely_true_positive",
                category="port_scan",
                severity=severity,
                confidence=0.91,
                reasoning="One source contacted multiple destination ports in a short period, consistent with reconnaissance.",
                investigations=["firewall_logs", "network_flow", "source_ip_reputation"],
                next_step="Review the targeted asset and confirm whether the source is an authorized scanner.",
                iocs=iocs,
            )

        malware_alert = _search(alert, "malware", "suspicious executable", "malicious hash", "unknown executable")
        if malware_alert or "hash" in alert.event_type.lower() or "edr" in alert.event_type.lower():
            return self._result(
                alert,
                classification="likely_true_positive",
                category="malware",
                severity="high",
                confidence=0.93,
                reasoning="Endpoint telemetry identifies a suspicious executable or file hash that requires investigation.",
                investigations=["endpoint_activity", "file_reputation", "process_tree"],
                next_step="Preserve endpoint evidence and investigate the file hash before considering containment.",
                iocs=iocs,
            )

        outbound_alert = _search(alert, "suspicious outbound", "unusual external", "unusual destination")
        if outbound_alert or ("outbound" in alert.event_type.lower() and alert.destination_ip):
            return self._result(
                alert,
                classification="likely_true_positive",
                category="suspicious_outbound_connection",
                severity="medium",
                confidence=0.82,
                reasoning="The endpoint initiated an outbound connection to an unusual external destination.",
                investigations=["firewall_logs", "dns_logs", "destination_reputation", "endpoint_activity"],
                next_step="Correlate the connection with the owning process and destination reputation.",
                iocs=iocs,
            )

        return self._result(
            alert,
            classification="needs_investigation",
            category="unknown",
            severity="medium",
            confidence=0.50,
            reasoning="The alert does not match a high-confidence baseline rule and needs analyst investigation.",
            investigations=["related_logs", "asset_context", "threat_intelligence"],
            next_step="Collect related logs and asset context before assigning a final disposition.",
            iocs=iocs,
        )

    @staticmethod
    def _result(
        alert: Alert,
        *,
        classification: str,
        category: str,
        severity: str,
        confidence: float,
        reasoning: str,
        investigations: list[str],
        next_step: str,
        iocs: list[str],
    ) -> TriageResult:
        """Construct and validate every rule result through the shared schema."""

        return TriageResult(
            alert_id=alert.alert_id,
            classification=classification,
            category=category,
            severity=severity,
            confidence=confidence,
            reasoning_summary=reasoning,
            extracted_iocs=iocs,
            required_investigations=investigations,
            recommended_next_step=next_step,
        )


class OptionalLLMTriageAdapter:
    """Placeholder for a provider-specific structured-output adapter."""

    def __init__(self, api_key: str | None, model: str | None) -> None:
        self.api_key = api_key
        self.model = model

    def triage(self, alert: Alert) -> TriageResult:
        """Signal that provider integration is intentionally deferred."""

        del alert
        raise LLMNotConfiguredError(
            "LLM triage is not implemented in Week 1; use the deterministic baseline."
        )
